swagger: "2.0"
info:
  description: "Droplead for Telesale"
  version: "1.0.0"
  title: "Droplead"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "eagarin@terrabit.co.th"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tododefined.krungsri.com"
basePath: "/v1"
tags:
- name: "droplead"
  description: "Droplead for all channels"

schemes:
- "https"
paths:
  /droplead:
    post:
      tags:
      - "droplead"
      summary: "Droplead to Telesale system"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "channel"
        in: "header"
        required: true
        type: "string"  
      - name: "key"
        in: "header"
        required: true
        type: "string"    
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Droplead"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              message: 
                type: "string"
                example: "success"
        "400":
          description: "Bad Request"
          schema:
            type: "object"
            properties:
              message: 
                type: "string"
                example: "Invlid Date format for appliedDate"
          

definitions:
  Droplead:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      crmCode:
        type: "string"
        description: "Predefined CRM Code"
        example: "999999"
      utmSource: 
        type: "string"
        description: "UTM Source"
        example: "Facebook"
      appliedDate:
        type: "string"
        description: "Applied Date"
        format: "date-time"
      dropPoint:
        type: "string"
        description: Channel Application Step/Point which customer left this apply form"
        example: "DropPoint#1"
      lastSessionDate:
        type: "string"
        description: "Last Update when customer left apply form"
        format: "date-time"
      lastScreen:
        type: "string"
        description: "Last KWA Screen"
        example: "Summary Page"
      firstName:
        type: "string"
        description: "Customer First Name"
        example: "ลิซ่า"
      surName:
        type: "string"
        description: "Customer Surname" 
        example: "รอดพลาย"
      mobilePhone:
        type: "string"
        description: "Mobile Phone"
        example: "0817779999"
      citizenId:
        type: "string"
        description: "Thai Idwentity ID"
        example: "3101300234560"
      occupation:
        type: "string"
        description: "Occupation"
        example: "รับจ้าง"
      jobType:
        type: "string"
        description: "Job Type"
        example: "Type1"
      income:
        type: "integer"
        description: "Income"
        format: "int64"
        example: "45000"  
      otherIncome:
        type: "integer"
        description: "Other Income"
        format: "int64"
        example: "18000"        
      totalIncome:
        type: "integer"
        description: "Total Income"
        format: "int64"
        example: "63000" 
      payrollFlag:  
        type: "string"
        description: "Payroll Flag"
        example: "X"
      companyName:  
        type: "string"
        description: "Company Name"
        example: "บริษัท ไทยผลิต จำกัด"  
      customerType:  
        type: "string"
        description: "Customer Type"
        example: "customer"
      email:
        type: "string"
        description: "Email"
        example: "lisa@thaipalid.co.th"
      jobAge:
        type: "number"
        description: "Job Age"
        format: "float"
        example: "2.5" 
      totalJobAge:
        type: "number"
        description: "Total Job Age"
        format: "float"
        example: "14.5"  
      installmentCreditLine:
        type: "number"
        description: "Installment Credit Line"
        format: "double"
        example: "10000" 
      interestRate:
        type: "number"
        description: "Interest Rate"
        format: "float"
        example: "3.5"   
      installment:
        type: "number"
        description: "Installment"
        format: "double"
        example: "999"  
      term:
        type: "number"
        description: "Term"
        format: "double"
        example: "999"    
      revolvingCreditLine:
        type: "number"
        description: "Revolving Credit Line"
        format: "double"
        example: "10000"  
      revolvingInterestRate:
        type: "number"
        description: "Revolving Interest Rate"
        format: "float"
        example: "1.5"   
      revolvingMinimumPayment:
        type: "number"
        description: "Revolving Minimum Payment"
        format: "double"
        example: "5000"    
      loanAccount:
        type: "string"
        description: "Loan Account"
        example: "9999999999"
      loanPaymentType:
        type: "string"
        description: "Loan Payment Type"
        example: "Type1"  
      loanRejectCode:
        type: "string"
        description: "Loan Reject Code"
        example: "xxx"    
      loanRejectDescription:
        type: "string"
        description: "Loan Reject Description"
        example: "Blacklist"  
      custom1:
        type: "string"
        description: "Additional Field for future use"
      custom2:
        type: "string"
        description: "Additional Field for future use"
      custom3:
        type: "string"
        description: "Additional Field for future use"
      custom4:
        type: "string"
        description: "Additional Field for future use"
      custom5:
        type: "string"
        description: "Additional Field for future use"
      custom6:
        type: "string"
        description: "Additional Field for future use"
      custom7:
        type: "string"
        description: "Additional Field for future use"
      custom8:
        type: "string"
        description: "Additional Field for future use"
      custom9:
        type: "string"
        description: "Additional Field for future use"
      custom10:
        type: "string"
        description: "Additional Field for future use"  
      custom11:
        type: "string"
        description: "Additional Field for future use"
      custom12:
        type: "string"
        description: "Additional Field for future use"
      custom13:
        type: "string"
        description: "Additional Field for future use"
      custom14:
        type: "string"
        description: "Additional Field for future use"
      custom15:
        type: "string"
        description: "Additional Field for future use"
      custom16:
        type: "string"
        description: "Additional Field for future use"
      custom17:
        type: "string"
        description: "Additional Field for future use"
      custom18:
        type: "string"
        description: "Additional Field for future use"
      custom19:
        type: "string"
        description: "Additional Field for future use"
      custom20:
        type: "string"
        description: "Additional Field for future use"   
      